services:
  db:
    image: postgres:16.11-alpine
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      PGTZ: UTC
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "$APP_CONFIG__DB__PORT:5432"
    container_name: ${APP_CONFIG__DB__CNT_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

secrets:
  db_password:
    file: ${APP_CONFIG__DB__PASSWORD_FILE}

volumes:
  db_data:


