services:
  db:
    image: postgres:16.11-alpine
    env_file:
      - src/.env
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      PGTZ: UTC
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
    container_name: github-clone-db
    volumes:
      - db_data:/var/lib/postgresql/data

secrets:
  db_password:
    file: ./src/secrets/db_password.txt

volumes:
  db_data:

